// filepath: /i:/website/3D_Portfolio/vite.config.ts
import { defineConfig } from 'vite';
// ...existing code...
export default defineConfig({
  base: '/fagun-with-bugs/', // adjust to match your repository name
  // other Vite configuration...
})
// ...existing code...
>>>>>>> a92b921 (Saving local changes before rebase)
=======
=======
// ...existing code...
>>>>>>> a92b921 (Saving local changes before rebase)
