// filepath: /i:/website/3D_Portfolio/vite.config.ts
import { defineConfig } from 'vite';
// ...existing code...
export default defineConfig({
  base: '/fagun-with-bugs/', // adjust to match your repository name
  // other Vite configuration...
})
// ...existing code...
